enum SharedPreferenceKey {
  TokenInfo,
  LastLoginEmail,
  ViewedIntro,
  Config,
  Profile,
  Feed,
  PostBackground,
  PopularUser,
  Notification,
  AllowNotification,
  SendEmail,
  SaveEmailAddress,
  DefaultAvatars,
  Popup,
  ReleaseVersionPopup,
  UserDisableVisibleVersionPopup,
  UserClickPopup
}
