name: base_flutter_bloc
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  #mutiple_language
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_lints: ^3.0.1
  injectable: ^2.1.2 # inject (DI)
  get_it: ^7.2.0 # inject (DI)
  dio: ^5.2.1+1
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.4
  overlay_support: ^2.1.0
  bloc: ^8.0.3
  base_bloc_module:
    path: ./base_bloc_module
  freezed_annotation: ^2.0.3
  #  firebase
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1
  flutter_facebook_auth: ^6.0.0
  # package info
  package_info_plus: ^5.0.1
  device_info_plus: ^9.0.2
  #Env
  flutter_dotenv: ^5.1.0
  #json anotation
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.9.0
  # loger
  logger: ^2.0.2+1
  retrofit: ^4.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.2
  build_runner: ^2.1.10
  flutter_gen_runner: any
  freezed: ^2.0.2
  json_serializable: ^6.7.0
  retrofit_generator: ^8.0.6
flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - env/
    - assets/images/
    - assets/svg/
    - assets/json/
    - fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
flutter_intl:
  enabled: true
  class_name: Languages
  arb_dir: lib/translations
  output_dir: lib/gen