name: base_flutter_bloc
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  #mutiple_language
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_lints: ^5.0.0
  injectable: ^2.5.0 # inject (DI)
  get_it: ^8.0.3 # inject (DI)
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  overlay_support: ^2.1.0
  bloc: ^8.1.4
  base_bloc_module:
    path: ./base_bloc_module
  freezed_annotation: ^2.4.4
  #  firebase
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  google_sign_in: ^6.2.2
  the_apple_sign_in: ^1.1.1
  flutter_facebook_auth: ^7.1.1
  # package info
  package_info_plus: ^8.1.2
  device_info_plus: ^11.2.0
  #Env
  flutter_dotenv: ^5.2.1
  #json anotation
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  # loger
  logger: ^2.5.0
  retrofit: ^4.4.1
  shared_preferences: ^2.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.2
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - env/
    - assets/images/
    - assets/svg/
    - assets/json/
    - fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
flutter_intl:
  enabled: true
  class_name: Languages
  arb_dir: lib/translations
  output_dir: lib/gen
