name: base_flutter_bloc
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  #mutiple_language
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  injectable: ^2.7.0 # inject (DI)
  get_it: ^9.1.1 # inject (DI)
  dio: ^5.7.0
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  overlay_support: ^2.1.0
  bloc: ^9.1.0
  base_bloc_module:
    path: ./base_bloc_module
  #  firebase
  #  firebase_auth: ^6.1.2
  #  firebase_core: ^4.2.1
  #  the_apple_sign_in: ^1.1.1
  #Env
  flutter_dotenv: ^6.0.0
  #json anotation
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  # loger
  logger: ^2.5.0
  retrofit: ^4.9.1
  http_parser: ^4.1.2
  path: ^1.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.9.1
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  json_serializable: ^6.11.2
  retrofit_generator: ^10.2.0
flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - env/
#    - assets/images/
#    - assets/svg/
#    - assets/json/
    - fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
flutter_intl:
  enabled: true
  class_name: Languages
  arb_dir: lib/translations
  output_dir: lib/gen
